import sys
from pathlib import Path

from services.file_reader import read_file
from services.data_profiler import profile_dataframe, detect_domain, detect_capabilities
from services.cleaning_engine import clean_dataframe
from services.metadata_builder import build_safe_metadata
from services.ollama_local_ai import enhance_metadata_with_ollama
from services.smart_ai_placeholder import (
    get_schema_suggestions as get_schema_suggestions_local,
    get_kpi_dashboard_suggestions as get_kpi_dashboard_suggestions_local,
)
from services.openai_smart_ai import (
    get_schema_suggestions as get_schema_suggestions_openai,
    get_kpi_dashboard_suggestions as get_kpi_dashboard_suggestions_openai,
    generate_dashboard_design_plan,
    generate_business_report,
)
from services.transformation_engine import apply_schema_suggestions
from services.suggestion_validator import validate_schema_suggestions, validate_kpi_suggestions
from services.kpi_engine import calculate_kpis
from services.dashboard_engine import build_dashboard_data
from services.report_engine import build_report_summary
from services.html_dashboard import write_html_dashboard
from utils.json_utils import save_json


def run_pipeline(input_file: str, business_context: str = "auto", objective: str = "auto-generate useful dashboard"):
    input_path = Path(input_file)
    project_name = input_path.stem
    output_dir = Path("output") / project_name
    output_dir.mkdir(parents=True, exist_ok=True)

    df = read_file(input_path)
    profile = profile_dataframe(df)
    profile["domain_detection"] = detect_domain(profile)
    profile["capabilities"] = detect_capabilities(profile)
    save_json(profile, output_dir / "01_data_profile.json")

    cleaned_df, cleaning_log = clean_dataframe(df)
    cleaned_df.to_csv(output_dir / "02_cleaned_data.csv", index=False)
    save_json(cleaning_log, output_dir / "02_cleaning_log.json")

    safe_metadata = build_safe_metadata(cleaned_df, business_context, objective)
    save_json(safe_metadata, output_dir / "03_safe_metadata_basic.json")

    safe_metadata = enhance_metadata_with_ollama(safe_metadata)
    save_json(safe_metadata, output_dir / "03_safe_metadata_for_schema_ai.json")

    try:
        schema_suggestions = get_schema_suggestions_openai(safe_metadata)
        schema_suggestions_source = "openai"
        print("Schema suggestions generated by OpenAI Smart AI.")
    except Exception as e:
        schema_suggestions = get_schema_suggestions_local(safe_metadata)
        schema_suggestions_source = "local_fallback"
        print(f"OpenAI Schema AI unavailable. Using local fallback. Reason: {e}")

    schema_suggestions["_source"] = schema_suggestions_source
    save_json(schema_suggestions, output_dir / "04_schema_suggestions_raw.json")

    schema_suggestions, schema_validation_log = validate_schema_suggestions(cleaned_df, schema_suggestions)
    save_json(schema_suggestions, output_dir / "04_schema_suggestions_validated.json")
    save_json(schema_validation_log, output_dir / "04_schema_validation_log.json")

    enriched_df, transformation_log = apply_schema_suggestions(cleaned_df, schema_suggestions)
    enriched_df.to_csv(output_dir / "05_enriched_data.csv", index=False)
    save_json(transformation_log, output_dir / "05_transformation_log.json")

    enriched_metadata = build_safe_metadata(enriched_df, business_context, objective)
    save_json(enriched_metadata, output_dir / "06_safe_metadata_basic.json")

    enriched_metadata = enhance_metadata_with_ollama(enriched_metadata)
    save_json(enriched_metadata, output_dir / "06_safe_metadata_for_kpi_ai.json")

    try:
        kpi_suggestions = get_kpi_dashboard_suggestions_openai(enriched_metadata)
        kpi_suggestions_source = "openai"
        print("KPI/dashboard suggestions generated by OpenAI Smart AI.")
    except Exception as e:
        kpi_suggestions = get_kpi_dashboard_suggestions_local(enriched_metadata)
        kpi_suggestions_source = "local_fallback"
        print(f"OpenAI KPI/Dashboard AI unavailable. Using local fallback. Reason: {e}")

    kpi_suggestions["_source"] = kpi_suggestions_source
    save_json(kpi_suggestions, output_dir / "07_kpi_dashboard_suggestions_raw.json")

    kpi_suggestions, kpi_validation_log = validate_kpi_suggestions(enriched_df, kpi_suggestions)
    save_json(kpi_suggestions, output_dir / "07_kpi_dashboard_suggestions_validated.json")
    save_json(kpi_validation_log, output_dir / "07_kpi_validation_log.json")

    kpi_results = calculate_kpis(enriched_df, kpi_suggestions)
    save_json(kpi_results, output_dir / "08_kpi_results.json")

    dashboard_data = build_dashboard_data(kpi_suggestions, kpi_results)
    save_json(dashboard_data, output_dir / "09_dashboard_data.json")

    try:
        dashboard_design_plan = generate_dashboard_design_plan(
            enriched_metadata,
            kpi_suggestions,
            dashboard_data,
        )
        dashboard_design_plan_source = "openai"
        print("Dashboard design plan generated by OpenAI Dashboard Architect AI.")
    except Exception as e:
        dashboard_design_plan = {
            "dashboard_title": dashboard_data.get("title", "Executive Analytics Dashboard"),
            "dashboard_objective": "Provide a decision-focused overview of the dataset.",
            "recommended_filters": [],
            "sections": [],
            "chart_decisions": [],
            "interaction_plan": {},
            "data_story": [],
            "design_notes": [f"Dashboard Architect AI unavailable. Reason: {e}"],
        }
        dashboard_design_plan_source = "local_fallback"
        print(f"OpenAI Dashboard Architect AI unavailable. Using fallback design plan. Reason: {e}")

    dashboard_design_plan["_source"] = dashboard_design_plan_source
    save_json(dashboard_design_plan, output_dir / "08_dashboard_design_plan.json")

    dashboard_data["design_plan"] = dashboard_design_plan
    dashboard_data["title"] = dashboard_design_plan.get("dashboard_title", dashboard_data.get("title", "Executive Analytics Dashboard"))
    dashboard_data["subtitle"] = dashboard_design_plan.get("dashboard_objective", dashboard_data.get("subtitle", "Auto-generated dashboard"))
    save_json(dashboard_data, output_dir / "09_dashboard_data_with_design.json")

    write_html_dashboard(dashboard_data, output_dir / "10_dashboard_preview.html")

    report_summary = build_report_summary(profile, safe_metadata, cleaning_log, transformation_log, kpi_results, dashboard_data)
    report_summary["dashboard_design_plan"] = dashboard_design_plan
    save_json(report_summary, output_dir / "11_report_summary.json")

    try:
        business_report = generate_business_report(report_summary)
        report_source = "openai"
        print("Business report generated by OpenAI Report AI.")
    except Exception as e:
        business_report = (
            "# Business Report\n\n"
            "The AI business report could not be generated. "
            "Please review the report summary JSON manually.\n\n"
            f"Reason: {e}\n"
        )
        report_source = "local_fallback"
        print(f"OpenAI Report AI unavailable. Using fallback report. Reason: {e}")

    report_markdown = f"<!-- report_source: {report_source} -->\n\n{business_report}\n"
    (output_dir / "12_ai_business_report.md").write_text(report_markdown, encoding="utf-8")

    print("Pipeline completed.")
    print(f"Project output folder: {output_dir.resolve()}")
    print(f"Dashboard preview: {(output_dir / '10_dashboard_preview.html').resolve()}")
    print(f"Dashboard JSON: {(output_dir / '09_dashboard_data.json').resolve()}")
    print(f"AI Business Report: {(output_dir / '12_ai_business_report.md').resolve()}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python main.py input/index_2.csv")
        sys.exit(1)
    run_pipeline(sys.argv[1])
