from __future__ import annotations

from typing import Any


def _round_number(value: Any, digits: int = 2) -> Any:
    """Round numeric values safely while leaving non-numeric values unchanged."""
    if isinstance(value, (int, float)):
        return round(value, digits)
    return value


def _summarize_chart(chart: dict[str, Any], limit: int = 5) -> dict[str, Any]:
    """Create a compact, safe summary of chart data for Report AI."""
    data = chart.get("data", []) or []
    x_field = chart.get("x_field")
    y_field = chart.get("y_field")

    top_items = []
    for row in data[:limit]:
        safe_row = {}
        if x_field in row:
            safe_row[x_field] = row.get(x_field)
        if y_field in row:
            safe_row[y_field] = _round_number(row.get(y_field))
        top_items.append(safe_row)

    return {
        "title": chart.get("title"),
        "type": chart.get("type"),
        "x_field": x_field,
        "y_field": y_field,
        "top_items": top_items,
        "record_count_in_chart": len(data),
    }


def build_report_summary(profile, metadata, cleaning_log, transformation_log, kpi_results, dashboard_data):
    """
    Build a safe report package.

    This function does not send or expose the raw dataset. It only summarizes:
    - dataset shape
    - cleaning actions
    - transformations
    - KPI cards
    - compact chart summaries
    - recommended report structure
    """
    kpi_cards = []
    findings = []

    for card in kpi_results.get("kpi_cards", []):
        title = card.get("title")
        value = _round_number(card.get("value"))
        kpi_cards.append({
            "title": title,
            "value": value,
            "format": card.get("format", "number"),
        })
        findings.append(f"{title}: {value}")

    chart_summaries = []
    for chart in dashboard_data.get("charts", []):
        summary = _summarize_chart(chart)
        chart_summaries.append(summary)
        if summary["top_items"]:
            findings.append(f"Top result for {summary['title']}: {summary['top_items'][0]}")

    dataset_summary = metadata.get("dataset_summary", {})

    return {
        "report_input_type": "safe_aggregated_summary_only",
        "dataset_overview": {
            "rows_before_cleaning": profile.get("row_count"),
            "rows_after_cleaning": cleaning_log.get("final_rows"),
            "columns_before_enrichment": profile.get("column_count"),
            "detected_domain": dataset_summary.get("possible_business_domain", "unknown"),
            "dashboard_title": dashboard_data.get("title", "Auto-Generated Business Dashboard"),
        },
        "data_quality_summary": {
            "cleaning_summary": cleaning_log,
            "data_quality_note": "The report is based on cleaned and transformed data generated by the local data engine.",
        },
        "transformation_summary": transformation_log,
        "main_kpis": kpi_cards,
        "chart_summaries": chart_summaries,
        "main_findings": findings,
        "recommended_report_sections": [
            "Executive Summary",
            "Dataset Overview",
            "Data Quality Findings",
            "Transformations Applied",
            "KPI Results",
            "Dashboard Insights",
            "Risks and Anomalies",
            "Recommendations",
            "Suggested Next Actions",
        ],
        "report_guidelines": {
            "tone": "professional, clear, business-focused",
            "avoid": [
                "Do not claim causation unless supported by the data.",
                "Do not mention raw private records.",
                "Do not invent business facts that are not in the summary.",
            ],
            "style": "Use headings and concise paragraphs. Include practical recommendations.",
        },
    }
